In [56]:
import pandas as pd

In [61]:
df_copy = pd.read_csv('/home/islam_tb/Documents/AlgerPlate/data/LP Data/project-2-at-2026-04-21-15-24-06e8bde7.csv', dtype={'text': str})
df_copy.head()

,annotation_id,annotator,created_at,id,img_name,lead_time,text,updated_at
0,1955,1,2026-04-19T16:23:32.197324Z,1952,/data/upload/2/6426d866-0a4ed302-img_0779_box0...,23.205,05624410516,2026-04-19T16:23:32.197413Z
1,1956,1,2026-04-19T16:23:58.280543Z,1953,/data/upload/2/6b4860ec-0a5bf5ea-img_1234_box0...,14.699,1270931221,2026-04-19T16:23:58.280635Z
2,1957,1,2026-04-19T16:24:09.247052Z,1954,/data/upload/2/aced3508-0a8fdbf9-img_1846_box0...,8.287,0372228143,2026-04-19T16:24:09.247146Z
3,1958,1,2026-04-19T16:24:24.625303Z,1955,/data/upload/2/078eee86-0a9c6e93-img_0108_box0...,12.458,06515810816,2026-04-19T16:24:24.625432Z
4,1959,1,2026-04-19T16:24:56.347542Z,1956,/data/upload/2/609fa80d-0a555df3-img_1303_box0...,28.514,2145911242,2026-04-19T16:24:56.347668Z

In [62]:
df_copy['text']

0       05624410516
1        1270931221
2        0372228143
3       06515810816
4        2145911242
           ...
2074    25029311316
2075     0489912309
2076     0659511909
2077     3004610809
2078    08770011916
Name: text, Length: 2079, dtype: str

In [63]:
analysis = pd.DataFrame({
    'Length': df_copy['text'].str.len(),
    'Year_Code': df_copy['text'].str[-4:-2],
    'Wilaya_Code': df_copy['text'].str[-2:]
})

# Example: Get the top 5 most frequent Wilayas
print(analysis['Wilaya_Code'].value_counts().head(5))

Wilaya_Code
16    1040
09     155
43     133
18     120
35     103
Name: count, dtype: int64

In [64]:
def reg_year(y):
    if int(y)>26:
        return '19'+y
    else:
        return '20'+y
    
analysis['Year_Code'] = analysis['Year_Code'].apply(reg_year)
analysis

      Length Year_Code Wilaya_Code
0         11      2005          16
1         10      2012          21
2         10      1981          43
3         11      2008          16
4         10      2012          42
...      ...       ...         ...
2074      11      2013          16
2075      10      2023          09
2076      10      2019          09
2077      10      2008          09
2078      11      2019          16

[2079 rows x 3 columns]

In [65]:
# Showing how many plates of each length belong to each Year
ct = pd.crosstab(analysis['Year_Code'], analysis['Length'])
print(ct)

Length     8   9    10   11  12
Year_Code
1954        0   0    1    0   0
1958        0   0    1    0   0
1967        0   0    1    0   0
1973        0   0    0    2   0
1975        0   0    2    0   0
1981        0   0    3    2   0
1982        0   0    2    0   0
1983        0   0    1    0   0
1984        0   0    7    1   0
1985        0   0    9    0   0
1986        0   0    9    4   0
1987        0   0    6    0   0
1989        0   1    0    4   0
1990        1   0    6    4   0
1991        0   0    8    0   0
1992        0   0    5    1   0
1993        0   0    6    0   0
1994        0   0    7    0   0
1995        0   0   10    3   0
1996        0   0   17    4   0
1997        0   0   19    6   0
1998        0   0   25    8   0
1999        1   0   36   12   0
2000        0   3   74   16   0
2001        0   0   44   10   0
2002        0   0   29    3   0
2003        0   0   20   13   0
2004        0   1   40   19   0
2005        0   0   38    7   0
2006        0   0   43   25   0
2007        0   1   56   20   0
2008        0   0   71   38   0
2009        0   0   52   31   0
2010        0   0   83   21   0
2011        0   0   66   34   0
2012        0   0  140   55   0
2013        0   1   70  137   1
2014        0   1   60  117   0
2015        0   0   41  109   0
2016        0   0   17   59   0
2017        0   0   14   30   0
2018        0   0   11   24   0
2019        0   0    9   21   0
2020        0   0    0    1   0
2021        0   0    3    1   0
2022        0   0    3   14   0
2023        0   0    5    9   0
2024        0   0    5   19   0
2025        0   0    0    8   0
2026        0   0    0    1   0

In [66]:
print(analysis['Length'].value_counts())

Length
10    1175
11     893
9        8
8        2
12       1
Name: count, dtype: int64

In [68]:
analysis[analysis['Length']==10]['Year_Code'].value_counts()

Year_Code
2012    140
2010     83
2000     74
2008     71
2013     70
2011     66
2014     60
2007     56
2009     52
2001     44
2006     43
2015     41
2004     40
2005     38
1999     36
2002     29
1998     25
2003     20
1997     19
1996     17
2016     17
2017     14
2018     11
1995     10
1986      9
1985      9
2019      9
1991      8
1984      7
1994      7
1990      6
1993      6
1987      6
2024      5
1992      5
2023      5
1981      3
2022      3
2021      3
1982      2
1975      2
1983      1
1958      1
1967      1
1954      1
Name: count, dtype: int64

In [71]:
df_copy = df_copy[df_copy['text'].str.len()<12]
df_copy.head(1)

,annotation_id,annotator,created_at,id,img_name,lead_time,text,updated_at
0,1955,1,2026-04-19T16:23:32.197324Z,1952,/data/upload/2/6426d866-0a4ed302-img_0779_box0...,23.205,05624410516,2026-04-19T16:23:32.197413Z

In [72]:
df_copy = df_copy.drop(columns=["annotation_id", "annotator", "created_at", "id", "lead_time", "updated_at"])
df_copy.head(1)

                                            img_name         text
0  /data/upload/2/6426d866-0a4ed302-img_0779_box0...  05624410516

In [73]:
def get_suffix_after_hyphen(text):
    # split(separator, maxsplit)
    # This splits the string at the first '-' and takes the second part [1]
    parts = text.split('-', 1)
    
    # Check if a hyphen actually exists to avoid IndexErrors
    return parts[1] if len(parts) > 1 else text

df_copy["file_name"] = df_copy["img_name"].apply(get_suffix_after_hyphen)
df_copy.head()

,img_name,text,file_name
0,/data/upload/2/6426d866-0a4ed302-img_0779_box0...,05624410516,0a4ed302-img_0779_box0.png
1,/data/upload/2/6b4860ec-0a5bf5ea-img_1234_box0...,1270931221,0a5bf5ea-img_1234_box0.png
2,/data/upload/2/aced3508-0a8fdbf9-img_1846_box0...,0372228143,0a8fdbf9-img_1846_box0.png
3,/data/upload/2/078eee86-0a9c6e93-img_0108_box0...,06515810816,0a9c6e93-img_0108_box0.png
4,/data/upload/2/609fa80d-0a555df3-img_1303_box0...,2145911242,0a555df3-img_1303_box0.png

In [74]:
df_copy = df_copy.drop(columns=["img_name"])
df_copy.head()

          text                   file_name
0  05624410516  0a4ed302-img_0779_box0.png
1   1270931221  0a5bf5ea-img_1234_box0.png
2   0372228143  0a8fdbf9-img_1846_box0.png
3  06515810816  0a9c6e93-img_0108_box0.png
4   2145911242  0a555df3-img_1303_box0.png

In [75]:
df_copy.to_csv('/home/islam_tb/Documents/AlgerPlate/data/LP Data/lp_dataset.csv', index=False)

In [ ]:
df_copy = pd.read_csv('/home/islam_tb/Documents/AlgerPlate/data/LP Data/lp_dataset.csv')
#df_copy['text'] = df_copy['text'].astype(str)
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 2007 entries, 0 to 2006
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       2007 non-null   str
 1   file_name  2007 non-null   str
dtypes: str(2)
memory usage: 31.5 KB