In [1]:
import pandas as pd

ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/islam_tb/Documents/AlgerPlate/.venv/lib64/python3.11/site-packages/traitlets/traitlets.py", line 632, in get
    value = obj._trait_values[self.name]
            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: '_control_lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/islam_tb/Documents/AlgerPlate/.venv/lib64/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/home/islam_tb/Documents/AlgerPlate/.venv/lib64/python3.11/site-packages/ipykernel/kernelbase.py", line 347, in dispatch_control
    async with self._control_lock:
               ^^^^^^^^^^^^^^^^^^
  File "/home/islam_tb/Documents/AlgerPlate/.venv/lib64/python3.11/site-packages/traitlets/traitlets.py", line 687, in __get__
    return t.cast(G, self.get(obj, cls))  # the G should encode the Optional
                     ^^^^^^^^^^^^^^^^^^
  File "/home/islam_tb/Documents/AlgerPlate/.venv/lib64/python3.11/site-packages/traitlets/traitlets.py", line 649, in get
    value = self._validate(obj, default)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/islam_tb/Documents/AlgerPlate/.venv/lib64/python3.11/site-packages/traitlets/traitlets.py", line 722, in _validate
    value = self.validate(obj, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/islam_tb/Documents/AlgerPlate/.venv/lib64/python3.11/site-packages/traitlets/traitlets.py", line 2311, in validate
    self.error(obj, value)
  File "/home/islam_tb/Documents/AlgerPlate/.venv/lib64/python3.11/site-packages/traitlets/traitlets.py", line 831, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The '_control_lock' trait of an IPythonKernel instance expected a Lock, not the NoneType None.

In [2]:
df = pd.read_csv('/home/islam_tb/Documents/AlgerPlate/data/project-2-at-2026-04-21-15-24-06e8bde7.csv')
df.head()

,annotation_id,annotator,created_at,id,img_name,lead_time,text,updated_at
0,1955,1,2026-04-19T16:23:32.197324Z,1952,/data/upload/2/6426d866-0a4ed302-img_0779_box0...,23.205,5624410516,2026-04-19T16:23:32.197413Z
1,1956,1,2026-04-19T16:23:58.280543Z,1953,/data/upload/2/6b4860ec-0a5bf5ea-img_1234_box0...,14.699,1270931221,2026-04-19T16:23:58.280635Z
2,1957,1,2026-04-19T16:24:09.247052Z,1954,/data/upload/2/aced3508-0a8fdbf9-img_1846_box0...,8.287,372228143,2026-04-19T16:24:09.247146Z
3,1958,1,2026-04-19T16:24:24.625303Z,1955,/data/upload/2/078eee86-0a9c6e93-img_0108_box0...,12.458,6515810816,2026-04-19T16:24:24.625432Z
4,1959,1,2026-04-19T16:24:56.347542Z,1956,/data/upload/2/609fa80d-0a555df3-img_1303_box0...,28.514,2145911242,2026-04-19T16:24:56.347668Z

In [8]:
def chg_name(name):
    return name[(name.find('-')+1):]

df['file_name'] = df['img_name'].apply(chg_name)
df.head()

,annotation_id,annotator,created_at,id,img_name,lead_time,text,updated_at,file_name
0,1955,1,2026-04-19T16:23:32.197324Z,1952,/data/upload/2/6426d866-0a4ed302-img_0779_box0...,23.205,5624410516,2026-04-19T16:23:32.197413Z,0a4ed302-img_0779_box0.png
1,1956,1,2026-04-19T16:23:58.280543Z,1953,/data/upload/2/6b4860ec-0a5bf5ea-img_1234_box0...,14.699,1270931221,2026-04-19T16:23:58.280635Z,0a5bf5ea-img_1234_box0.png
2,1957,1,2026-04-19T16:24:09.247052Z,1954,/data/upload/2/aced3508-0a8fdbf9-img_1846_box0...,8.287,372228143,2026-04-19T16:24:09.247146Z,0a8fdbf9-img_1846_box0.png
3,1958,1,2026-04-19T16:24:24.625303Z,1955,/data/upload/2/078eee86-0a9c6e93-img_0108_box0...,12.458,6515810816,2026-04-19T16:24:24.625432Z,0a9c6e93-img_0108_box0.png
4,1959,1,2026-04-19T16:24:56.347542Z,1956,/data/upload/2/609fa80d-0a555df3-img_1303_box0...,28.514,2145911242,2026-04-19T16:24:56.347668Z,0a555df3-img_1303_box0.png

In [10]:
df_copy = df.copy()
df_copy.head()

,annotation_id,annotator,created_at,id,img_name,lead_time,text,updated_at,file_name
0,1955,1,2026-04-19T16:23:32.197324Z,1952,/data/upload/2/6426d866-0a4ed302-img_0779_box0...,23.205,5624410516,2026-04-19T16:23:32.197413Z,0a4ed302-img_0779_box0.png
1,1956,1,2026-04-19T16:23:58.280543Z,1953,/data/upload/2/6b4860ec-0a5bf5ea-img_1234_box0...,14.699,1270931221,2026-04-19T16:23:58.280635Z,0a5bf5ea-img_1234_box0.png
2,1957,1,2026-04-19T16:24:09.247052Z,1954,/data/upload/2/aced3508-0a8fdbf9-img_1846_box0...,8.287,372228143,2026-04-19T16:24:09.247146Z,0a8fdbf9-img_1846_box0.png
3,1958,1,2026-04-19T16:24:24.625303Z,1955,/data/upload/2/078eee86-0a9c6e93-img_0108_box0...,12.458,6515810816,2026-04-19T16:24:24.625432Z,0a9c6e93-img_0108_box0.png
4,1959,1,2026-04-19T16:24:56.347542Z,1956,/data/upload/2/609fa80d-0a555df3-img_1303_box0...,28.514,2145911242,2026-04-19T16:24:56.347668Z,0a555df3-img_1303_box0.png

In [11]:
df_copy = df_copy.drop(columns=['annotation_id', 'annotator', 'created_at', 'id', 'lead_time', 'updated_at'])
df_copy.head()

,img_name,text,file_name
0,/data/upload/2/6426d866-0a4ed302-img_0779_box0...,5624410516,0a4ed302-img_0779_box0.png
1,/data/upload/2/6b4860ec-0a5bf5ea-img_1234_box0...,1270931221,0a5bf5ea-img_1234_box0.png
2,/data/upload/2/aced3508-0a8fdbf9-img_1846_box0...,372228143,0a8fdbf9-img_1846_box0.png
3,/data/upload/2/078eee86-0a9c6e93-img_0108_box0...,6515810816,0a9c6e93-img_0108_box0.png
4,/data/upload/2/609fa80d-0a555df3-img_1303_box0...,2145911242,0a555df3-img_1303_box0.png

In [12]:
df_copy = df_copy.drop(columns=['img_name'])
df_copy.head()

         text                   file_name
0  5624410516  0a4ed302-img_0779_box0.png
1  1270931221  0a5bf5ea-img_1234_box0.png
2   372228143  0a8fdbf9-img_1846_box0.png
3  6515810816  0a9c6e93-img_0108_box0.png
4  2145911242  0a555df3-img_1303_box0.png

In [17]:
df_copy = df_copy.drop_duplicates(subset=['file_name'], keep='first')
df_copy.head()

         text                   file_name
0  5624410516  0a4ed302-img_0779_box0.png
1  1270931221  0a5bf5ea-img_1234_box0.png
2   372228143  0a8fdbf9-img_1846_box0.png
3  6515810816  0a9c6e93-img_0108_box0.png
4  2145911242  0a555df3-img_1303_box0.png

In [22]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 2008 entries, 0 to 2078
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       2008 non-null   str
 1   file_name  2008 non-null   str
dtypes: str(2)
memory usage: 47.1 KB

In [21]:
df_copy['text'] = df_copy['text'].astype(str)

In [29]:
analysis = pd.DataFrame({
    'Length': df_copy['text'].str.len(),
    'Year_Code': df_copy['text'].str[-4:-2],
    'Wilaya_Code': df_copy['text'].str[-2:]
})

# Example: Get the top 5 most frequent Wilayas
print(analysis['Wilaya_Code'].value_counts().head(5))

Wilaya_Code
16    1001
09     151
43     128
18     117
35      97
Name: count, dtype: int64

In [32]:
def reg_year(y):
    if int(y)>26:
        return '19'+y
    else:
        return '20'+y
    
analysis['Year_Code'] = analysis['Year_Code'].apply(reg_year)
analysis

      Length Year_Code Wilaya_Code
0         10      2005          16
1         10      2012          21
2          9      1981          43
3         10      2008          16
4         10      2012          42
...      ...       ...         ...
2074      11      2013          16
2075       9      2023          09
2076       9      2019          09
2077      10      2008          09
2078      10      2019          16

[2008 rows x 3 columns]

In [36]:
# Showing how many plates of each length belong to each Year
ct = pd.crosstab(analysis['Year_Code'], analysis['Length'])
print(ct)

Length     7   8   9    10  11  12
Year_Code
1954        1   0   0    0   0   0
1958        0   1   0    0   0   0
1967        0   0   1    0   0   0
1973        0   0   0    2   0   0
1975        0   0   2    0   0   0
1981        0   0   1    3   0   0
1982        0   0   2    0   0   0
1983        0   0   1    0   0   0
1984        0   0   3    5   0   0
1985        0   0   5    4   0   0
1986        0   0   7    6   0   0
1987        0   1   5    0   0   0
1989        0   0   1    4   0   0
1990        0   2   3    6   0   0
1991        0   0   7    1   0   0
1992        0   0   5    1   0   0
1993        0   3   2    1   0   0
1994        0   0   7    0   0   0
1995        1   0   9    2   0   0
1996        0   0  15    5   0   0
1997        0   0  21    3   0   0
1998        0   0  15   17   0   0
1999        0   3  21   23   0   0
2000        0   8  50   33   0   0
2001        0   6  24   22   0   0
2002        2   1  20    9   0   0
2003        0   2  17   14   0   0
2004        0   1  25   32   0   0
2005        1   2  19   21   0   0
2006        1   0  23   41   0   0
2007        0   4  26   46   0   0
2008        0   2  26   61  15   0
2009        0   2  22   48   7   0
2010        0   2  29   68   1   0
2011        0   3  23   55  17   0
2012        0   0  43  107  37   0
2013        1   4  28  105  59   1
2014        0   1  36   83  48   0
2015        0   2  42   84  20   0
2016        0   1  21   51   1   0
2017        0   1  18   22   2   0
2018        0   2  10   22   1   0
2019        0   0  10   15   5   0
2020        0   0   0    1   0   0
2021        0   0   3    1   0   0
2022        1   2   7    1   5   0
2023        0   0   8    6   0   0
2024        2   3  12    3   2   0
2025        0   0   2    2   4   0
2026        0   0   0    0   1   0

In [38]:
df_copy.to_csv('/home/islam_tb/Documents/AlgerPlate/data/LP Data/lp_dataset.csv', index=False)